name: publish

on: [push]

jobs:
  compare:
    runs-on: ubuntu-latest
    outputs:
      flag: ${{ steps.set-flag.outputs.flag }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
            
      - name: Log in to the Container registries
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: Compare images for changes
        id: set-flag
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          source .github/workflows/utils.sh
          version="3.12"
          repo="rjpadilla/nginx-tags:${{ matrix.arch }}"
          base="rjpadilla/alpine-tags:${{ matrix.arch }}"
          docker pull -q $base &>/dev/null
          docker pull -q $repo &>/dev/null
          basesha=$(docker image inspect $base | jq --raw-output '.[0].RootFS.Layers|.[]')
          reposha=$(docker image inspect $repo | jq --raw-output '.[0].RootFS.Layers|.[]')
          echo "base sha:$basesha repo sha:$reposha"
          # [[ $basesha != *$reposha* ]] && echo "::set-output name=flag::true" || echo "no changes" 
          [[ $reposha == *$basesha* ]] && echo "no changes" || echo "::set-output name=flag::true"
  # images:
  #   needs: compare
  #   runs-on: ubuntu-latest
  #   outputs:
  #     build: ${{ steps.set-build.outputs.build }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       arch: [amd64, arm, arm64]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Log in to the Container registries
  #       run: |
  #         docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  #         docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      
  #     - name: Build docker image
  #       if: ${{ needs.compare.outputs.flag }}
  #       id: set-build
  #       run: |
  #         export DOCKER_CLI_EXPERIMENTAL=enabled
  #         echo "**************0*************"
  #         version="3.12"
  #         case ${{ matrix.arch }} in
  #           amd64) : "amd64/alpine:$version" ;;
  #           arm) : "balenalib/raspberry-pi-alpine:$version" ;;
  #           arm64) : "arm64v8/alpine:$version" ;;
  #         esac
  #         image="$_"
  #         repo="rjpadilla/alpine-tags:${{ matrix.arch }}"
  #         date="$(date +%Y%m%d%H%M)"
  #         docker build -t ghcr.io/$repo --build-arg IMAGE=$image . 
  #         docker tag ghcr.io/$repo docker.io/$repo
  #         docker tag ghcr.io/$repo ghcr.io/$repo-$date
  #         docker tag docker.io/$repo docker.io/$repo-$date
  #         docker push ghcr.io/$repo
  #         docker push docker.io/$repo
  #         docker push ghcr.io/$repo-$date
  #         docker push docker.io/$repo-$date
  #         docker images
  #         echo "::set-output name=build::true"
  # manifests:
  #   needs: images
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       registry: [docker.io, ghcr.io]
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Log in to the Container registries
  #       run: |
  #         docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  #         docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
  #     - name: Deploying manifest to Container Registries
  #       if: ${{ needs.images.outputs.build }}
  #       run: |
  #         repo="${{ matrix.registry }}/rjpadilla/alpine"
  #         date="$(date +%Y%m%d%H%M)"
  #         docker manifest create $repo:latest $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
  #         docker manifest create $repo:$date $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
  #         docker manifest annotate $repo:latest $repo-tags:arm --os linux --arch arm 
  #         docker manifest annotate $repo:$date $repo-tags:arm --os linux --arch arm 
  #         docker manifest inspect $repo:latest
  #         docker manifest push $repo:latest
  #         docker manifest push $repo:$date